### ISSUE TITLE
Functionality outside any function

### ISSUE THREAD

**Issue by herbdool** [Graham-72/simple_mailsystem#3]
At the beginning of the admin file there's some things going on, including a config_save() that's not in a function. Presumably it means this will happen everytime the file is loaded regardless. It's better to put this in a function.

**Comment by Graham-72** [comment]
It seems to happen every time it is run, which is/was the intention.

**Comment by Graham-72** [comment]
@herbdool Thanks for pointing this out because it has made me revisit the code and remove some unnecessary parts, including the config file specifically for simple_mailsystem. I think the new release 1.x-1.0.2 has this fixed.
